const API_BASE_URL_PROD = 'https://api.ardent-industry.com'
const API_BASE_URL_LOCAL = 'http://localhost:3001/api'

const API_BASE_URL = process?.env?.NODE_ENV === 'development'
  ? API_BASE_URL_LOCAL
  : API_BASE_URL_PROD

const SOL_COORDINATES = [0, 0, 0]
const COLONIA_COORDINATES = [-9530.5, -910.28125, 19808.125]

const COMMODITY_FILTER_MAX_DAYS_AGO_DEFAULT = '30'
const COMMODITY_FILTER_FLEET_CARRIER_DEFAULT = 'excluded'
const COMMODITY_FILTER_MIN_VOLUME_DEFAULT = 1000

module.exports = {
  API_BASE_URL,
  SOL_COORDINATES,
  COLONIA_COORDINATES,
  COMMODITY_FILTER_MAX_DAYS_AGO_DEFAULT,
  COMMODITY_FILTER_FLEET_CARRIER_DEFAULT,
  COMMODITY_FILTER_MIN_VOLUME_DEFAULT
}
