import getConfig from 'next/config'

// publicRuntimeConfig provides isomorphic access to specified env vars
const { publicRuntimeConfig } = getConfig()
const API_BASE_URL = publicRuntimeConfig?.API_BASE_URL ?? 'https://api.ardent-industry.com'

const SOL_COORDINATES = [0, 0, 0]
const COLONIA_COORDINATES = [-9530.5, -910.28125, 19808.125]

const COMMODITY_FILTER_MAX_DAYS_AGO_DEFAULT = '7'
const COMMODITY_FILTER_FLEET_CARRIER_DEFAULT = 'included'
const COMMODITY_FILTER_MIN_VOLUME_DEFAULT = 1000
const COMMODITY_FILTER_LOCATION_DEFAULT = 'Any location'
const COMMODITY_FILTER_DISTANCE_DEFAULT = 'Any distance'
const COMMODITY_FILTER_DISTANCE_WITH_LOCATION_DEFAULT = 100
const NO_DEMAND_TEXT = '-'

module.exports = {
  API_BASE_URL,
  SOL_COORDINATES,
  COLONIA_COORDINATES,
  COMMODITY_FILTER_MAX_DAYS_AGO_DEFAULT,
  COMMODITY_FILTER_FLEET_CARRIER_DEFAULT,
  COMMODITY_FILTER_MIN_VOLUME_DEFAULT,
  COMMODITY_FILTER_LOCATION_DEFAULT,
  COMMODITY_FILTER_DISTANCE_DEFAULT,
  COMMODITY_FILTER_DISTANCE_WITH_LOCATION_DEFAULT,
  NO_DEMAND_TEXT
}
