name: Deploy Ardent Website to Production

# This deployment script assumes the following are configured in GitHub actions:
#
#  SSH_PRIVATE_KEY [secret]
#  DEPLOY_HOST [variable]
#  DEPLOY_USER [variable]
#  DEPLOY_DIR [variable]
#  AWS_SECRET_ACCESS_KEY [secret]
#  AWS_ACCESS_KEY_ID [variable]
#  AWS_CLOUDFRONT_REGION [variable]
#  AWS_CLOUDFRONT_DISTRIBUTION_ID [variable]
#
# It also assumes the service has been previously run using pm2:
#
#  pm2 start npm --name "{repository name}" -- run start
#  pm2 save

on:
  push:
    branches: [ "main" ]

env:
  SERVICE_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i --delete"
        SOURCE: "./"
        REMOTE_HOST: ${{ vars.DEPLOY_HOST }}
        REMOTE_USER: ${{ vars.DEPLOY_USER }}
        TARGET: "${{ vars.DEPLOY_DIR }}/${{ env.SERVICE_NAME }}"
        EXCLUDE: ".git*, *.md, LICENSE, node_modules/"
        SCRIPT_AFTER: |
          cd "${{ vars.DEPLOY_DIR }}/${{ env.SERVICE_NAME }}"
          npm install
          npm run build
          pm2 restart "${{ env.SERVICE_NAME }}"
          echo $RSYNC_STDOUT
    - name: Invalidate CloudFront cache
      uses: chetan/invalidate-cloudfront-action@v2
      env:
        DISTRIBUTION: ${{ vars.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
        PATHS: "/*"
        AWS_REGION: ${{ vars.AWS_CLOUDFRONT_REGION }}
        AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}